name: FurnitureEngine
version: '2.0'
main: com.mira.furnitureengine.FurnitureEngine
api-version: 1.16
load: STARTUP
softdepend: [ GSit, Sittable, WorldGuard ]
author: Gabby
description: Allows you to make custom usable furniture.
website: www.nightrealm.ga

commands:
  furnitureengine:
    description: Main Plugin command.
    aliases: [fe]
    permission: furnitureengine.admin

permissions:
  furnitureengine.blockbreak:
    default: true
  furnitureengine.blockplace:
    default: true
  furnitureengine.admin:
    default: op
  furnitureengine.*:
    default: op
    children:
      furnitureengine.admin: true
      furnitureengine.blockbreak: true
      furnitureengine.blockplace: true
